### ISSUE TITLE
Configure github workflow

### ISSUE THREAD

**Issue by BlitGaming** [kognise/arpchat#10]
I think this will help determine which commits are suitable for assembly and which are not.

https://docs.github.com/en/actions/using-workflows/triggering-a-workflow

**Comment by kognise** [comment]
At some point I'll probably yoink [this workflow](https://github.com/kognise/overengineering/blob/main/.github/workflows/deploy.yaml), slap a matrix on it, and use that.

**Comment by kognise** [comment]
Donesies! >w<
