### ISSUE TITLE
Use Ethertype reserved for experimentation instead of IPv4 Ethertype

### ISSUE THREAD

**Issue by charasyn** [kognise/arpchat#4]
> i'm planning on experimenting with and adding settings for different arp packet types, since some routers might filter out the malformed ip packets i'm currently using.

Looking at [the list of Ethertype values](https://www.iana.org/assignments/ieee-802-numbers/ieee-802-numbers.xhtml), it appears that `88B5` and `88B6` are reserved for experimentation. From https://standards-oui.ieee.org/ethertype/eth.txt and referring to `88B5`:
```
Local Experimental EtherType 1 as defined in IEEE Std 802.  This EtherType
value is available for public use and for prototype and vendor-specific    
protocol development. 
```

I think it would probably make more sense to use one of these as the protocol type in the ARP packet instead of IPv4. Thoughts?

**Comment by kognise** [comment]
arriving at an arpchat near you in several minutes:

![](https://doggo.ninja/pjpy2L.png)
