### ISSUE TITLE
"Error getting channel" on linux (CAP_NET_RAW)

### ISSUE THREAD

**Issue by mrkeuz** [kognise/arpchat#6]
Really cool and fun project! Thanks! 🚀

### Issue
- Run `arpchat` 
- Select interface 
- On any key pressing `Error getting channel`

![image](https://user-images.githubusercontent.com/6247921/159581814-a6c6015e-3fa5-4e65-905b-ec6ff35388f0.png)

### Solution

Seems executable file should have `CAP_NET_RAW` capability and solved via:

```shell
sudo setcap CAP_NET_RAW+ep /path/to/arpchat
```

It would be good to add this to documentation.

### Env
`cargo +nightly build`
`cargo 1.60.0-nightly (95bb3c92b 2022-01-18)`
`Ubuntu 20.04.4`  5.4.0-104-generic

**Comment by kognise** [comment]
Great point-out, thanks! Added to the README.
